### ISSUE TITLE
SQLite3 Question

### ISSUE THREAD

**Issue by ShizuCarry** [CentauriSoldier/SQLite3-for-Lua#2]
Hey i'm trying to print things from my data base but i don't know what to write and where it should be (in update,draw ?)
http://lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki
A friend gave me this but each time i try to use a db:[something] it say it don't understand it.

         require('SQL3.sqlite3');
--local db = sqlite3.open(love.filesystem.getWorkingDirectory() .. "/test.db")
--local db = sqlite3.open("test.db");
local db = sqlite3.open(love.filesystem.getSaveDirectory().."/test.db")

function love.load()
 
    a = db:nrows('SELECT * FROM Manga')
  for i, v in pairs(a) do
    print(i, v)
  end
  
end

Exemple of a model i've tried (with a db call "test.db") an idea about what's wrong ? :)

**Comment by CentauriSoldier** [comment]
Sorry, this is unrelated to Dox and best asked on the LOVE forum.

**Comment by CentauriSoldier** [comment]
Unrelated issue.

**Comment by CentauriSoldier** [comment]
Please look at the intro page for this project, there is an example on there for how to setup the plugin properly. You must require the script in your project.

As far as how to do a proper query, I suggest reading up on SQLite3 here.
[]((https://www.sqlite.org/))

You can view tutorials here.
[](http://www.sqlitetutorial.net/)
